version: "3"

services:
  mysql:
    image: mysql:8
    restart: always
    volumes:
      - /var/lib/docker/volumes/nest-dip-db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: db
    ports:
      - "3306:3306"

  nest-dip:
    build: .
    restart: always
    container_name: nest-dip
    image: nest-dip:v1
    environment:
      - DB_USER=root
      - DB_PASSWORD=123456
      - DB_HOST=mysql
      - DB_DATABASE=db
      - NODE_ENV=dev
    depends_on:
      - mysql
    ports:
      - "8000:3000"
