version: "3"

services:
  mysql:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: testDB
    ports:
      - "3306:3306"
    volumes:
      - nestJS_DB:/var/lib/mysql

  nest-dip:
    build: .
    restart: always
    environment:
      - DB_USER=root
      - DB_PASSWORD=123456
      - DB_HOST=mysql
      - DB_DATABASE=testDB
      - NODE_ENV=dev
    depends_on:
      - mysql
    ports:
      - "8000:3000"
volumes:
  nestJS_DB:

