const TYPES = {
    DATABASE_SERVICE: Symbol.for("DATABASE_SERVICE"),
    DATABASE_POOL: Symbol.for("DATABASE_POOL"),
    BASE_REPOSITORY_SERVICE: Symbol.for("BASE_REPOSITORY_SERVICE"),
    USER_REPOSITORY_SERVICE: Symbol.for("USER_REPOSITORY_SERVICE"),
};

export { TYPES };